### ISSUE TITLE
Cannot read property 'onlyExec' of undefined

### ISSUE THREAD

**Issue by tcs-apeters** [mpneuried/iggy#23]
d.selected@https://sb.brendisol.com/dynasite/vendor/plugins/iggy/js/iggy.js 9:14467  

```
ollection.get(b)), this.multiSelect || this.close(), !1
}, d.prototype.selected = function(a) {
        return null != a.onlyExec ? void(null != a && "function" == typeof a.exec && a.exec()) : (this.searchcoll.remove(a), this.result.
```

**Comment by mpneuried** [comment]
![bildschirmfoto 2015-06-10 um 10 43 29](https://cloud.githubusercontent.com/assets/300631/8078378/c1da22c0-0f5d-11e5-8893-2a885acf712a.png)

**Comment by CitySim** [comment]
a is undefined
![bildschirmfoto 2015-06-10 um 11 01 09](https://cloud.githubusercontent.com/assets/109395/8078758/1b04a648-0f60-11e5-8c6e-c72908c147fd.png)

**Comment by CitySim** [comment]
different error in the system, this is caused by clicking on the "no facet found"-link. 
![bildschirmfoto 2015-06-12 um 13 39 22](https://cloud.githubusercontent.com/assets/109395/8129321/75b383c6-1108-11e5-90b4-bdd0737a3a2c.png)
but gets a log from this issue in the new version, so posting it in here

`Issue #23: No id - Class:d - Event:mousedown - InnerHTML:no result for "fsfsfds"``

**Cannot read property 'set' of undefined** (callstack from old/last version)

![bildschirmfoto 2015-06-12 um 13 37 47](https://cloud.githubusercontent.com/assets/109395/8129306/40106a86-1108-11e5-8b6b-42e1c7e4e041.png)
