### ISSUE TITLE
Add "Search" Button

### ISSUE THREAD

**Issue by mpneuried** [mpneuried/iggy#58]
![bildschirmfoto 2016-11-29 um 15 47 56](https://cloud.githubusercontent.com/assets/300631/20714736/36b01e82-b64d-11e6-82e4-1f0fb8496d72.png)

**Comment by mpneuried** [comment]
Add a optinal "Search" Button that triggers a custom Event.

**Comment by mpneuried** [comment]
options:
```js
searchButton: {
    template: "<i class='fa fa-search'></i>Search!",
    event: "search",
    pullRight: false
}
```

**Comment by trietz** [comment]
Button sieht leider nicht so aus wie im beispiel.
Bitte ähnlich oder steuerbar wie hier:

<div class="btn btn-primary fa fa-search js-search" style="padding: 7px 9px 8px 9px;"></div>

Bei Fragen bitte kurz anrufen.

**Comment by mpneuried** [comment]
Generell hat der Button eine Css Klasse und kann nach belieben gestylt werden. Ich werde ihn aber morgen früh optisch etwas anpassen

**Comment by mpneuried** [comment]
Ich habe den Button angepasst. Generell könnt ich das auch noch selbst fein tunen über die css KLasse `.search-btn`

**Comment by trietz** [comment]
Hi,

Vielen Dank fürs anpassen.

Ich würde viel lieber eigene Klassen angeben, ich möchte die von Bootsstrap
btn verwenden.

Ist das für dich nicht viel einfacher?

Greetz
Tim

Am 26.01.2017 um 07:30 schrieb M. Peter <notifications@github.com>:

Ich habe den Button angepasst. Generell könnt ich das auch noch selbst fein
tunen über die css KLasse .search-btn

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/mpneuried/iggy/issues/58#issuecomment-275317184>, or mute
the thread

**Comment by mpneuried** [comment]
Ist bereits drin, hatte ich nur vergessen zu dokumentieren ...
siehe https://github.com/mpneuried/iggy/commit/08fa269edf56e49689837178bf0209fd1c7cc90c?diff=unified#diff-04c6e90faac2675aa89e2176d2eec7d8R24
